name = "subtitle-agent"
main = "src/worker.ts"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

[observability]
  [observability.logs]
  enabled = true

# Environment variables - Use wrangler secrets for sensitive data
[vars]
NODE_ENV = "production"

# Use wrangler secrets to set these securely:
# wrangler secret put CLOUDFLARE_API_TOKEN
# wrangler secret put CLOUDFLARE_API_EMAIL  
# wrangler secret put CLOUDFLARE_ACCOUNT_ID
# wrangler secret put OPENAI_API_KEY
# wrangler secret put YOUTUBE_API_KEY

# For development, you can use .env.local file


