name = "subtitle-agent"
main = "src/worker.ts"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

[observability]
  [observability.logs]
  enabled = true

# Node.js compatibility for Mastra dependencies
[env.production.vars]
NODE_ENV = "production"


