name = "subtitle-agent"
main = "src/worker.ts"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat"]

[observability]
  [observability.logs]
  enabled = true

# Environment variables
[vars]
NODE_ENV = "production"
# Add your API keys here or use wrangler secrets
# OPENAI_API_KEY = "your-openai-api-key"
# YOUTUBE_API_KEY = "your-youtube-api-key"


