name = "subtitle-agent"
main = ".mastra/output/index.mjs"
compatibility_date = "2025-08-13"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
  [observability.logs]
  enabled = true

[build]
command = "npm run build"


